"""
Blog workflow state definitions for LangGraph.

This module defines the serializable state structures used by the LangGraph workflow,
replacing the complex CorrelationState from planner.py.
"""

from typing import TypedDict, List, Dict, Optional, Any


class Topic(TypedDict):
    """Represents a single blog post topic."""
    title: str
    slug: str
    source_kb_id: str
    abstract: Optional[str]


class BlogState(TypedDict):
    """Complete state for the blog generation workflow."""
    config: Any
    # --- Inputs & Configuration (passed at start) ---
    kb_article_path: str
    force_reingest: bool
    correlation_id: str

    # --- Ingestion State ---
    kb_content: Optional[str]              # Full text of the KB article
    ingestion_success: bool                # Status flag
    db_collection: Any                     # ChromaDB Collection object handle

    # --- Topic Iteration State (Multi-Topic Enhancement) ---
    topics: List[Topic]                    # Generated by TopicIdentificationAgent
    topic_index: int                       # Index of the *next* topic to be processed (Acts as loop counter)
    current_topic: Optional[Topic]         # The topic currently being worked on

    # --- Generation State (Per-Topic) ---
    current_outline: Optional[Dict]
    introduction: Optional[str]
    sections: Optional[List[Dict]]
    content: Optional[str]
    seo_metadata: Optional[Dict]
    final_markdown: Optional[str]
    gist_metadata: Optional[Dict]
    file_path: Optional[str]

    # --- Duplication Check State ---
    duplication_check_passed: Optional[bool]

    # --- Control & Resilience ---
    errors: List[str]
    retry_attempt: int
# DOCGEN:LLM-FIRST@v4