from __future__ import annotations

# Test Full Job Happy Path
# This file was generated by tools/test_refactor.py


def invalid_workflow_yaml():
    """Invalid workflow YAML to test validation"""
    return {
        "name": "broken_workflow",
        "version": "1.0.0",
        "steps": [
            {
                "id": "step1",
                "agent": "nonexistent_agent",  # Agent doesn't exist
                "params": {}
            }
        ]
    }

def run_all_tests():
    """Run all tests with detailed reporting"""
    import sys
    
    print("=" * 80)
    print("UCOP Workflow Engine Test Suite - Task 2")
    print("=" * 80)
    print()
    
    # Run with pytest
    exit_code = pytest.main([
        __file__,
        "-v",  # Verbose
        "--tb=short",  # Short traceback
        "--durations=10",  # Show 10 slowest tests
        "-k", "test_",  # Run all test functions
        "--asyncio-mode=auto"  # Enable async tests
    ])
    
    if exit_code == 0:
        print("\n" + "=" * 80)
        print("✓ ALL TESTS PASSED")
        print("=" * 80)
    else:
        print("\n" + "=" * 80)
        print("✗ SOME TESTS FAILED")
        print("=" * 80)
    
    return exit_code

def run_tests():
    """Run all Task 3 tests."""
    print("=" * 80)
    print("Task 3: Ops Console, UI, and Workflow Generator Tests")
    print("=" * 80)

    # Run pytest
    pytest.main([
        __file__,
        "-v",
        "--tb=short",
        "-k", "TestOpsConsole or TestWebUI or TestWorkflowGenerator or TestTask3"
    ])

def sample_workflow():
    """Create sample workflow definition."""
    return {
        "id": "test_workflow",
        "name": "Test Workflow",
        "description": "Test workflow for unit tests",
        "nodes": [
            {"id": "start", "agent": "ingest_kb_node", "type": "agent"},
            {"id": "process", "agent": "identify_topics_node", "type": "agent"},
            {"id": "end", "agent": "write_file_node", "type": "agent"}
        ],
        "edges": [
            {"from": "start", "to": "process", "type": "sequential"},
            {"from": "process", "to": "end", "type": "sequential"}
        ],
        "timeout": 300
    }

def sample_workflow_yaml():
    """Valid workflow YAML for testing"""
    return {
        "name": "test_blog_workflow",
        "version": "1.0.0",
        "steps": [
            {
                "id": "ingest",
                "agent": "ingest_kb_node",
                "params": {"source": "test_docs"}
            },
            {
                "id": "identify",
                "agent": "identify_topics_node",
                "params": {"max_topics": 5}
            },
            {
                "id": "generate",
                "agent": "section_writer_node",
                "params": {"style": "technical"}
            }
        ]
    }
