from __future__ import annotations

# Test Core And Utils
# This file was generated by tools/test_refactor.py


def _get(bus, names):
    for n in names:
        if hasattr(bus, n):
            return getattr(bus, n)
    return None

def _load_gate():
    m = importlib.import_module("src.engine.completeness_gate")
    Gate = getattr(m, "CompletenessGate", None)
    if Gate:
        inst = Gate()
        fn = getattr(inst, "is_complete", None) or getattr(inst, "evaluate", None) or getattr(inst, "validate", None)
        if fn:
            return lambda payload: fn(payload)
    for name in ["is_complete", "evaluate", "validate"]:
        fn = getattr(m, name, None)
        if callable(fn):
            return lambda payload: fn(payload)
    pytest.skip("No completeness gate found")

def _load_merge():
    m = importlib.import_module("src.engine.aggregator")
    Agg = getattr(m, "Aggregator", None)
    if Agg:
        inst = Agg()
        fn = getattr(inst, "merge", None) or getattr(inst, "aggregate", None)
        if fn:
            return lambda payload: fn(payload)
    fn = getattr(m, "aggregate", None) or getattr(m, "merge", None)
    if fn:
        return lambda payload: fn(payload)
    pytest.skip("No aggregator found")

def _load_selector():
    m = importlib.import_module("src.core.ollama")
    for attr in ["OllamaClient", "Router", "Client", "ModelSelector"]:
        if hasattr(m, attr):
            obj = getattr(m, attr)
            try:
                inst = obj()
                for name in ["select", "route", "choose", "get_client"]:
                    if hasattr(inst, name):
                        fn = getattr(inst, name)
                        return lambda: fn("test-task")
            except Exception:
                pass
    for name in ["select_model", "choose_model", "get_client"]:
        if hasattr(m, name):
            fn = getattr(m, name)
            return lambda: fn("test-task")
    pytest.skip("No obvious selection function/class in src.core.ollama")

def _no_network(monkeypatch):
    def _block(*a, **k):
        raise RuntimeError("Network disabled in perf tests")
    try:
        import socket
        monkeypatch.setattr(socket, "create_connection", _block, raising=False)
    except Exception:
        pass

def _sample_docs(n=30):
    rnd = random.Random(42)
    items = []
    for i in range(n):
        items.append({
            "title": f"Doc {i}",
            "summary": "lorem ipsum",
            "tags": ["a","b","c"][0: rnd.randint(1,3)],
            "score": rnd.random(),
        })
    return items

def check_file_exists(file_path: str) -> Tuple[bool, str]:
    """Check if a file exists."""
    path = Path(file_path)
    if path.exists():
        return True, f"[OK] {file_path}"
    else:
        return False, f"[FAIL] {file_path} - MISSING"

def check_import(module_path: str, item: str) -> Tuple[bool, str]:
    """Check if a module can be imported."""
    try:
        exec(f"from {module_path} import {item}")
        return True, f"[OK] {module_path}.{item}"
    except ImportError as e:
        return False, f"[FAIL] {module_path}.{item} - {str(e)}"

def generate_slug(text: str) -> str:
    """Generate URL-safe slug from text (extracted logic)."""
    # Convert to lowercase
    slug = text.lower()

    # Remove special characters
    slug = re.sub(r'[^\w\s-]', '', slug)

    # Replace spaces and multiple hyphens with single hyphen
    slug = re.sub(r'[-\s]+', '-', slug)

    # Remove leading/trailing hyphens
    slug = slug.strip('-')

    # Limit length
    if len(slug) > 100:
        slug = slug[:100].rstrip('-')

    # Ensure not empty
    if not slug:
        slug = "untitled"

    return slug

def get_output_path(job_id: str, title: str, blog_mode: bool) -> Path:
    """Get output path based on blog mode (extracted logic)."""
    output_dir = Path("./output")

    # Generate slug from title
    slug = generate_slug(title)

    # Apply blog switch logic
    if blog_mode:
        # Blog mode ON: ./output/{slug}/index.md
        output_path = output_dir / slug / "index.md"
    else:
        # Blog mode OFF: ./output/{slug}.md
        output_path = output_dir / f"{slug}.md"

    return output_path

def main():
    """Run all installation checks."""
    print_header("UCOP v10 Installation Verification")

    all_passed = True

    # Check 1: Core v10 Engine Files
    print_header("1. Checking v10 Engine Files")
    engine_files = [
        "src/engine/__init__.py",
        "src/engine/executor.py",
        "src/engine/input_resolver.py",
        "src/engine/aggregator.py",
        "src/engine/completeness_gate.py",
        "src/engine/context_merger.py",
        "src/engine/agent_tracker.py",
        "src/engine/exceptions.py",
    ]

    for file in engine_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 2: Enhanced Utilities
    print_header("2. Checking Enhanced Utilities")
    util_files = [
        "src/utils/citation_tracker.py",
        "src/utils/duplication_detector.py",
    ]

    for file in util_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 3: API Validator
    print_header("3. Checking API Validator")
    validator_files = [
        "src/agents/code/api_validator.py",
    ]

    for file in validator_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 4: Template Schemas
    print_header("4. Checking Template Schemas")
    schema_files = [
        "templates/schema/blog_template.yaml",
        "templates/schema/code_template.yaml",
    ]

    for file in schema_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 5: API Reference Data
    print_header("5. Checking API Reference Data")
    data_files = [
        "data/api_reference/python_stdlib.json",
    ]

    for file in data_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 6: Test Files
    print_header("6. Checking Test Suite")
    test_files = [
        "tests/unit/test_engine.py",
        "tests/integration/test_unified_executor.py",
    ]

    for file in test_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 7: Modified Files
    print_header("7. Checking Modified Files")
    modified_files = [
        "ucop_cli.py",
        "src/orchestration/job_execution_engine.py",
        "src/web/app.py",
    ]

    for file in modified_files:
        passed, message = check_file_exists(file)
        print(message)
        all_passed = all_passed and passed

    # Check 8: Import Tests
    print_header("8. Testing Imports")

    # Add current directory to path
    sys.path.insert(0, str(Path.cwd()))

    imports_to_test = [
        ("src.engine", "UnifiedJobExecutor"),
        ("src.engine", "JobConfig"),
        ("src.engine", "CompletenessGate"),
        ("src.engine", "InputResolver"),
        ("src.engine", "OutputAggregator"),
        ("src.engine", "AgentTracker"),
        ("src.utils.citation_tracker", "CitationTracker"),
        ("src.utils.duplication_detector", "EnhancedDuplicationDetector"),
    ]

    for module, item in imports_to_test:
        passed, message = check_import(module, item)
        print(message)
        all_passed = all_passed and passed

    # Final Result
    print_header("Installation Verification Result")

    if all_passed:
        print("[SUCCESS] All v10 components are properly installed.\n")
        print("Next Steps:")
        print("  1. Run tests: pytest tests/unit/test_engine.py -v")
        print("  2. Try direct CLI: python ucop_cli.py create blog_generation --input 'Test Topic'")
        print("  3. Start web UI: python start_web_ui.py")
        print(f"\n{'=' * 60}\n")
        return 0
    else:
        print("[FAIL] Some components are missing or cannot be imported.\n")
        print("Troubleshooting:")
        print("  1. Ensure you're in the project root directory")
        print("  2. Reinstall: pip install -r requirements.txt")
        print("  3. Check extraction: unzip -l unified_generator_v10_implementation.zip")
        print(f"\n{'=' * 60}\n")
        return 1

def mock_agent_registry():
    """Mock agent registry with test agents"""
    class MockRegistry:
        def __init__(self):
            self.agents = {
                "ingest_kb_node": {
                    "id": "ingest_kb_node",
                    "version": "1.0.0",
                    "inputs": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "source": {"type": "string"}
                            },
                            "required": ["source"]
                        }
                    },
                    "outputs": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "documents": {"type": "array"}
                            }
                        }
                    },
                    "checkpoints": [
                        {
                            "name": "before_execution",
                            "mutable_params": ["source"]
                        }
                    ]
                },
                "identify_topics_node": {
                    "id": "identify_topics_node",
                    "version": "1.0.0",
                    "inputs": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "documents": {"type": "array"},
                                "max_topics": {"type": "integer"}
                            },
                            "required": ["documents"]
                        }
                    },
                    "outputs": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "topics": {"type": "array"}
                            }
                        }
                    },
                    "checkpoints": []
                },
                "section_writer_node": {
                    "id": "section_writer_node",
                    "version": "1.0.0",
                    "inputs": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "topics": {"type": "array"},
                                "style": {"type": "string"}
                            }
                        }
                    },
                    "outputs": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "content": {"type": "string"}
                            }
                        }
                    },
                    "checkpoints": [
                        {
                            "name": "approval_gate",
                            "mutable_params": ["style"]
                        }
                    ]
                }
            }
        
        def get_contract(self, agent_id: str):
            return self.agents.get(agent_id)
    
    return MockRegistry()

def print_header(text: str):
    """Print formatted header."""
    print(f"\n{'=' * 60}")
    print(f"  {text}")
    print(f"{'=' * 60}\n")

def pytest_configure(config):
    os.environ.setdefault("PYTHONHASHSEED", "42")
    random.seed(42)
    os.environ.setdefault("NO_NETWORK", "1")
    os.environ.setdefault("PERF_RESULTS_PATH", "reports/perf_results.json")
    os.environ.setdefault("PERF_ITERS", "10")
    os.environ.setdefault("PERF_WARMUP", "3")

def run_all_tests():
    """Run all tests and report results"""
    print("\n" + "="*70)
    print("OLLAMA MODEL ROUTER INTEGRATION TESTS")
    print("="*70)
    print("Testing the router integration in UCOP v10...")

    tests = [
        ("Import Router", test_router_import),
        ("Initialize Router", test_router_initialization),
        ("Model Recommendations", test_model_recommendation),
        ("Config Integration", test_config_integration),
        ("LLMService Integration", test_llm_service_integration),
        ("Model Helper", test_model_helper),
    ]

    results = []
    for test_name, test_func in tests:
        try:
            passed = test_func()
            results.append((test_name, passed))
        except Exception as e:
            logger.error(f"Test '{test_name}' crashed: {e}")
            results.append((test_name, False))

    # Summary
    print("\n" + "="*70)
    print("TEST SUMMARY")
    print("="*70)

    passed = sum(1 for _, result in results if result)
    total = len(results)

    for test_name, result in results:
        status = "✅ PASS" if result else "❌ FAIL"
        print(f"{status}: {test_name}")

    print("\n" + "="*70)
    print(f"RESULTS: {passed}/{total} tests passed")
    print("="*70)

    if passed == total:
        print("\n🎉 All tests passed! Router is fully integrated.")
        print("\nNext steps:")
        print("1. Start Ollama: ollama serve")
        print("2. Pull some models: ollama pull llama2")
        print("3. Run UCOP: python ucop_cli.py create blog_generation --input 'Python Tips'")
        print("4. Check logs for: 'Selected model' messages")
        return 0
    else:
        print(f"\n⚠️  {total - passed} test(s) failed.")
        print("\nTroubleshooting:")
        print("1. Make sure all files are present")
        print("2. Check Python imports")
        print("3. See OLLAMA_ROUTER_INTEGRATION.md for details")
        return 1

def setup_device(device: str = None) -> str:
    """Setup computation device with CUDA auto-detection (extracted logic)."""
    import os

    # Priority 1: Explicit parameter
    if device:
        return device

    # Priority 2: Environment variable
    env_device = os.getenv("FORCE_DEVICE")
    if env_device:
        return env_device

    # Priority 3: Auto-detect CUDA
    try:
        import torch
        if torch.cuda.is_available():
            return "cuda"
        else:
            return "cpu"
    except ImportError:
        return "cpu"
    except Exception:
        return "cpu"

def test_agents_module_loads():
    import importlib
    mod = importlib.import_module("src.agents.agents_complete")
    assert mod is not None

def test_aggregator_merges_dicts():
    m = importlib.import_module("src.engine.aggregator")
    # Prefer class Aggregator; else function aggregate/merge
    Aggregator = getattr(m, "Aggregator", None)
    fn = getattr(m, "aggregate", None) or getattr(m, "merge", None)

    sample = [
        {"title": "A", "tags": ["x"]},
        {"summary": "S", "tags": ["y"]},
    ]

    if Aggregator:
        agg = Aggregator()
        merge = getattr(agg, "merge", None) or getattr(agg, "aggregate", None)
        if not merge:
            pytest.skip("Aggregator has no merge/aggregate method")
        out = merge(sample)
    elif callable(fn):
        # accept either *args or single list param
        if len(inspect.signature(fn).parameters) == 1:
            out = fn(sample)
        else:
            out = fn(*sample)
    else:
        pytest.skip("No Aggregator/aggregate found")

    assert isinstance(out, dict), "Merged output should be a dict"
    assert out.get("title") == "A"
    assert out.get("summary") == "S"
    assert set(out.get("tags", [])) >= {"x", "y"}

def test_aggregator_throughput():
    merge = _load_merge()
    payload = [{"title": "A", "tags": ["x"]},
               {"summary": "S", "tags": ["y"]},
               {"body": "..."}]
    timings = time_call(lambda: merge(payload))
    res = record_result("engine", "aggregator.merge", timings)
    assert res["mean"] < 0.05, f"aggregator mean {res['mean']:.3f}s"

def test_blog_switch():
    """Test Requirement #6: Blog switch controls output path."""
    print("\n" + "="*60)
    print("TEST #6: Blog Switch Output Paths")
    print("="*60)

    # Test 1: Blog mode OFF (default)
    print("\n1. Testing Blog mode OFF...")
    title = "Python Classes Tutorial"
    output_path_off = get_output_path("test-job-1", title, blog_mode=False)

    print(f"   Input: '{title}'")
    print(f"   Blog mode: OFF")
    print(f"   Output path: {output_path_off}")
    print(f"   Expected format: ./output/{{slug}}.md")

    # Verify format
    assert output_path_off.suffix == ".md", "Wrong file extension"
    assert "index.md" not in str(output_path_off), "Should not have index.md"
    assert "python-classes-tutorial" in str(output_path_off).lower(), "Slug not generated correctly"
    print(f"   [OK] Format correct: {output_path_off.name}")

    # Test 2: Blog mode ON
    print("\n2. Testing Blog mode ON...")
    output_path_on = get_output_path("test-job-2", title, blog_mode=True)

    print(f"   Input: '{title}'")
    print(f"   Blog mode: ON")
    print(f"   Output path: {output_path_on}")
    print(f"   Expected format: ./output/{{slug}}/index.md")

    # Verify format
    assert output_path_on.name == "index.md", "Should be index.md"
    assert "python-classes-tutorial" in str(output_path_on.parent).lower(), "Slug directory not created"
    print(f"   [OK] Format correct: {output_path_on}")

    # Test 3: Slug generation with special characters
    print("\n3. Testing slug generation with special chars...")
    title_special = "Python's Best Practices & Tips (2024)"
    output_path_special = get_output_path("test-job-3", title_special, blog_mode=False)
    slug = output_path_special.stem

    print(f"   Input: '{title_special}'")
    print(f"   Generated slug: {slug}")

    # Verify slug is clean
    assert re.match(r'^[a-z0-9-]+$', slug), f"Slug contains invalid characters: {slug}"
    assert slug == "pythons-best-practices-tips-2024", f"Unexpected slug: {slug}"
    print(f"   [OK] Slug clean and URL-safe: {slug}")

    # Test 4: Deterministic slugs
    print("\n4. Testing deterministic slug generation...")
    output_path_a = get_output_path("job-a", title_special, blog_mode=False)
    output_path_b = get_output_path("job-b", title_special, blog_mode=False)

    assert output_path_a.stem == output_path_b.stem, "Slugs not deterministic"
    print(f"   [OK] Same input produces same slug: {output_path_a.stem}")

    # Test 5: Various titles
    print("\n5. Testing various title formats...")
    test_cases = [
        ("Simple Title", "simple-title"),
        ("Title With   Spaces", "title-with-spaces"),
        ("CamelCaseTitle", "camelcasetitle"),
        ("Title-With-Hyphens", "title-with-hyphens"),
        ("123 Numbers 456", "123-numbers-456"),
        ("Special!@#$%^&*()Chars", "specialchars"),
        ("   Leading and Trailing   ", "leading-and-trailing"),
        ("Multiple---Hyphens", "multiple-hyphens"),
    ]

    for title, expected_slug in test_cases:
        slug = generate_slug(title)
        assert slug == expected_slug, f"Failed for '{title}': got '{slug}', expected '{expected_slug}'"
        print(f"   [OK] '{title}' -> '{slug}'")

    # Test 6: Compare blog ON vs OFF
    print("\n6. Comparing blog mode ON vs OFF...")
    test_title = "My Awesome Blog Post"
    path_off = get_output_path("job", test_title, blog_mode=False)
    path_on = get_output_path("job", test_title, blog_mode=True)

    print(f"   Title: '{test_title}'")
    print(f"   OFF: {path_off}")
    print(f"   ON:  {path_on}")

    # Verify both use same slug
    assert generate_slug(test_title) in str(path_off), "OFF path missing slug"
    assert generate_slug(test_title) in str(path_on), "ON path missing slug"

    # Verify different structures
    assert path_off.name.endswith(".md") and path_off.name != "index.md", "OFF should be {slug}.md"
    assert path_on.name == "index.md", "ON should be index.md"
    assert path_on.parent.name == generate_slug(test_title), "ON should have slug directory"

    print(f"   [OK] Both modes working correctly")

    print("\n" + "="*60)
    print("[OK] BLOG SWITCH TEST PASSED")
    print("="*60)

def test_completeness_gate_minimal():
    m = importlib.import_module("src.engine.completeness_gate")
    Gate = getattr(m, "CompletenessGate", None)
    fn = getattr(m, "is_complete", None) or getattr(m, "evaluate", None) or getattr(m, "validate", None)

    # minimal payload; Kilo can expand with real required fields after reading code
    payload = {"artifacts": [], "meta": {}}

    if Gate:
        gate = Gate()
        check = getattr(gate, "is_complete", None) or getattr(gate, "evaluate", None) or getattr(gate, "validate", None)
        if not check:
            pytest.skip("Gate has no is_complete/evaluate/validate")
        res = check(payload)
    elif callable(fn):
        params = inspect.signature(fn).parameters
        res = fn(payload) if len(params) == 1 else fn(**{"state": payload})
    else:
        pytest.skip("No completeness gate found")

    assert isinstance(res, (bool, dict)), "Gate should return bool or result dict"

def test_completeness_gate_speed():
    gate = _load_gate()
    payload = {"artifacts": _sample_docs(30), "meta": {"required": ["title","summary"]}}
    timings = time_call(lambda: gate(payload))
    res = record_result("engine", "completeness_gate", timings)
    assert res["mean"] < 0.05, f"gate mean {res['mean']:.3f}s"

def test_config_integration():
    """Test 4: Is router integrated with Config?"""
    print("\n" + "="*70)
    print("TEST 4: Config Integration")
    print("="*70)
    try:
        from src.core import Config
        config = Config()

        # Check if new config options exist
        has_smart_routing = hasattr(config, 'enable_smart_routing')
        has_ollama_model = hasattr(config, 'ollama_topic_model')

        if has_smart_routing:
            print(f"✅ Config has 'enable_smart_routing': {config.enable_smart_routing}")
        else:
            print("❌ Config missing 'enable_smart_routing'")

        if has_ollama_model:
            print(f"✅ Config has 'ollama_topic_model': {config.ollama_topic_model}")
        else:
            print("❌ Config missing 'ollama_topic_model'")

        return has_smart_routing and has_ollama_model
    except Exception as e:
        print(f"❌ Failed to test config: {e}")
        return False

def test_cuda_detection():
    """Test Requirement #10: CUDA default if detected else CPU."""
    print("\n" + "="*60)
    print("TEST #10: CUDA Auto-Detection")
    print("="*60)

    # Test 1: Default detection
    print("\n1. Testing default CUDA detection...")
    device = setup_device()
    print(f"   [OK] Device detected: {device}")
    assert device in ["cpu", "cuda"], f"Invalid device: {device}"

    # Test 2: Explicit CPU override
    print("\n2. Testing explicit CPU override...")
    device_cpu = setup_device(device="cpu")
    print(f"   [OK] Device set to: {device_cpu}")
    assert device_cpu == "cpu", "CPU override failed"

    # Test 3: Explicit CUDA override
    print("\n3. Testing explicit CUDA override...")
    device_cuda = setup_device(device="cuda")
    print(f"   [OK] Device set to: {device_cuda}")
    assert device_cuda == "cuda", "CUDA override failed"

    # Test 4: Environment variable
    print("\n4. Testing environment variable...")
    import os
    os.environ["FORCE_DEVICE"] = "cpu"
    device_env = setup_device()
    print(f"   [OK] Device from env: {device_env}")
    assert device_env == "cpu", "Env override failed"
    del os.environ["FORCE_DEVICE"]

    print("\n" + "="*60)
    print("[OK] CUDA DETECTION TEST PASSED")
    print("="*60)

    return device

def test_dashboard_has_auto_topic_checkbox():
    """Test that dashboard.html contains auto-topic checkbox."""
    dashboard_path = Path("src/web/templates/dashboard.html")
    content = dashboard_path.read_text()

    assert 'id="job-auto-topic"' in content, "Auto-topic checkbox missing"
    assert 'type="checkbox"' in content, "Checkbox type missing"
    assert 'Auto-derive topic' in content or 'auto-topic' in content.lower(), "Auto-topic label missing"

def test_dashboard_has_context_pickers():
    """Test that dashboard.html contains all context pickers."""
    dashboard_path = Path("src/web/templates/dashboard.html")
    content = dashboard_path.read_text()

    # Check for all context pickers
    assert 'id="job-kb-path"' in content, "KB path picker missing"
    assert 'id="job-docs-path"' in content, "Docs path picker missing"
    assert 'id="job-blog-path"' in content, "Blog path picker missing"
    assert 'id="job-api-path"' in content, "API path picker missing"
    assert 'id="job-tutorial-path"' in content, "Tutorial path picker missing"

    # Check for browse buttons
    assert 'onclick="browsePath' in content, "Browse buttons missing"
    assert content.count('Browse') >= 5, "Not enough browse buttons (should be at least 5)"

def test_dashboard_has_template_dropdown():
    """Test that dashboard.html contains template dropdown."""
    dashboard_path = Path("src/web/templates/dashboard.html")
    assert dashboard_path.exists(), "dashboard.html not found"

    content = dashboard_path.read_text()

    # Check for template dropdown
    assert 'id="job-template"' in content, "Template dropdown missing"
    assert '<select id="job-template"' in content, "Template select element missing"
    assert 'blog_default' in content, "Blog default template option missing"
    assert 'code_' in content, "Code template options missing"
    assert 'kb_' in content, "KB template options missing"
    assert 'docs_' in content, "Docs template options missing"

def test_dashboard_js_sends_all_fields():
    """Test that dashboard.js sends all required fields."""
    js_path = Path("src/web/static/js/dashboard.js")
    assert js_path.exists(), "dashboard.js not found"

    content = js_path.read_text()

    # Check that form submission includes all fields
    assert 'template_name' in content, "template_name not sent"
    assert 'auto_topic' in content, "auto_topic not sent"
    assert 'docs_path' in content, "docs_path not sent"
    assert 'blog_path' in content, "blog_path not sent"
    assert 'api_path' in content, "api_path not sent"
    assert 'tutorial_path' in content, "tutorial_path not sent"

def test_event_bus_basic():
    m = importlib.import_module("src.core.event_bus")
    Bus = getattr(m, "EventBus", None) or getattr(m, "MessageBus", None)
    if not Bus:
        pytest.skip("No EventBus-like class found")
    bus = Bus()

    calls = []
    subscribe = _get(bus, ["subscribe", "on", "add_listener"])
    publish  = _get(bus, ["publish", "emit", "send", "post"])
    unsubscribe = _get(bus, ["unsubscribe", "off", "remove_listener"])

    if not (subscribe and publish):
        pytest.skip("subscribe/publish not found on bus")

    def handler(data=None, **_):
        calls.append(data if data is not None else True)

    topic = "unit.test"
    subscribe(topic, handler)
    publish(topic, {"ok": True})

    assert calls, "Handler was not called after publish()"

    if unsubscribe:
        unsubscribe(topic, handler)
        calls.clear()
        publish(topic, {"ok": False})
        assert not calls, "Handler called after unsubscribe()"

def test_fastapi_latency_smoke():
    try:
        from fastapi.testclient import TestClient
    except Exception:
        pytest.skip("fastapi not installed for tests")

    app = _load_app()
    client = TestClient(app)
    candidates = ["/health", "/ping", "/"]
    target = None
    for p in candidates:
        try:
            r = client.get(p)
            if 200 <= r.status_code < 300:
                target = p
                break
        except Exception:
            pass
    if not target:
        pytest.skip("No 2xx health-like endpoint found")

    timings = time_call(lambda: client.get(target))
    res = record_result("web", f"GET {target}", timings)
    assert res["mean"] < 0.25, f"web mean latency too high: {res['mean']:.3f}s"

def test_health_endpoint():
    app = _load_app()
    try:
        from fastapi.testclient import TestClient
    except Exception:
        pytest.skip("fastapi not installed for tests")
    client = TestClient(app)
    for path in ("/health", "/ping", "/"):
        r = client.get(path)
        if r.status_code < 500:
            assert 200 <= r.status_code < 300
            return
    pytest.skip("No health-like route returned 2xx")

def test_job_detail_has_log_modal_functions():
    """Test that job_detail.js contains log modal functions."""
    js_path = Path("src/web/static/js/job_detail.js")
    assert js_path.exists(), "job_detail.js not found"

    content = js_path.read_text()

    # Check for modal functions
    assert 'showLogModal' in content, "showLogModal function missing"
    assert 'closeLogModal' in content, "closeLogModal function missing"
    assert 'downloadJSON' in content, "downloadJSON function missing"
    assert '/api/agents/' in content, "Agent API call missing"

def test_llm_service_integration():
    """Test 5: Is router integrated with LLMService?"""
    print("\n" + "="*70)
    print("TEST 5: LLMService Integration")
    print("="*70)
    try:
        from src.services import LLMService
        from src.core import Config

        config = Config()
        config.llm_provider = "OLLAMA"
        config.enable_smart_routing = True

        # Try to initialize LLMService
        # Note: This might fail if Ollama is not running, but that's okay
        try:
            llm_service = LLMService(config)

            # Check if router is initialized
            has_router = hasattr(llm_service, 'model_router')
            if has_router and llm_service.model_router:
                print("✅ LLMService has model_router initialized")
                print(f"   Router enabled: {llm_service.model_router.enable_smart_routing}")
                return True
            elif has_router:
                print("⚠️  LLMService has model_router attribute but it's None")
                print("   (This is okay if Ollama is not running)")
                return True
            else:
                print("❌ LLMService missing model_router")
                return False
        except ConnectionError:
            print("⚠️  Could not connect to Ollama")
            print("   (Router will still work once Ollama is started)")
            return True

    except Exception as e:
        print(f"❌ Failed to test LLMService: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_log_modal_shows_json_io():
    """Test that log modal displays JSON input/output."""
    js_path = Path("src/web/static/js/job_detail.js")
    content = js_path.read_text()

    # Check for JSON display elements
    assert 'json-output' in content or 'JSON.stringify' in content, "JSON output display missing"
    assert 'Input' in content and 'Output' in content, "Input/Output sections missing"
    assert 'Download' in content or 'download' in content.lower(), "Download functionality missing"

def test_model_helper():
    """Test 6: Can agents use the model helper?"""
    print("\n" + "="*70)
    print("TEST 6: Model Helper for Agents")
    print("="*70)
    try:
        from src.utils.model_helper import get_optimal_model, TaskType, initialize_model_helper
        from src.services.model_router import OllamaModelRouter

        # Initialize helper
        router = OllamaModelRouter(enable_smart_routing=True)
        initialize_model_helper(router)

        # Test convenience function
        model = get_optimal_model(
            task="Write Python code",
            agent_name="TestAgent"
        )
        print(f"✅ get_optimal_model() works: {model}")

        # Test TaskType constants
        model = get_optimal_model(
            task=TaskType.CODE_GENERATION,
            agent_name="CodeAgent"
        )
        print(f"✅ TaskType constants work: {model}")

        return True
    except Exception as e:
        print(f"❌ Failed to test model helper: {e}")
        return False

def test_model_recommendation():
    """Test 3: Can router recommend models?"""
    print("\n" + "="*70)
    print("TEST 3: Model Recommendations")
    print("="*70)
    try:
        from src.services.model_router import OllamaModelRouter
        router = OllamaModelRouter(enable_smart_routing=True)

        test_cases = [
            ("Write Python code", "CodeAgent"),
            ("Write blog article", "ContentWriter"),
            ("Debug JavaScript", "CodeReviewer"),
            ("Quick chat", "ChatBot"),
        ]

        for task, agent in test_cases:
            model = router.recommend_model(task, agent)
            print(f"✅ Task: '{task}'")
            print(f"   Agent: {agent}")
            print(f"   → Model: {model}")

        return True
    except Exception as e:
        print(f"❌ Failed to get recommendations: {e}")
        return False

def test_modules_import(mod):
    importlib.import_module(mod)

def test_ollama_selection_speed(monkeypatch):
    selector = _load_selector()
    def _no_network(*a, **k):
        return {"ok": True, "mock": True}
    try:
        import src.core.ollama as ollama
        for name in ["send", "request", "generate", "chat"]:
            if hasattr(ollama, name):
                monkeypatch.setattr(ollama, name, _no_network, raising=False)
    except Exception:
        pass
    timings = time_call(lambda: selector())
    res = record_result("core", "ollama.select", timings)
    assert res["mean"] < 0.02, f"ollama selection mean {res['mean']:.3f}s"

def test_pipeline_order_matches_config():
    """Test that pipeline view would match config order (placeholder test)."""
    # This would require checking the job detail page rendering
    # For now, just verify config file exists
    config_path = Path("config/agents.yaml")
    assert config_path.exists(), "agents.yaml config not found"

    content = config_path.read_text()
    assert 'pipeline:' in content or 'agents:' in content, "Pipeline definition missing from config"

def test_placeholder_mesh_components_exist():
    import importlib
    mod = importlib.import_module("src.mesh")
    # Just assert module loads (detailed tests come after core is unified)
    assert mod is not None

def test_router_import():
    """Test 1: Can we import the router?"""
    print("\n" + "="*70)
    print("TEST 1: Import Router")
    print("="*70)
    try:
        from src.services.model_router import OllamaModelRouter
        print("✅ Successfully imported OllamaModelRouter")
        return True
    except ImportError as e:
        print(f"❌ Failed to import router: {e}")
        return False

def test_router_initialization():
    """Test 2: Can we initialize the router?"""
    print("\n" + "="*70)
    print("TEST 2: Initialize Router")
    print("="*70)
    try:
        from src.services.model_router import OllamaModelRouter
        router = OllamaModelRouter(enable_smart_routing=True)
        print(f"✅ Router initialized successfully")
        print(f"   Available models: {len(router.available_models)}")
        if router.available_models:
            print(f"   Models: {', '.join(router.available_models[:5])}...")
        else:
            print("   ⚠️  No models found - is Ollama running?")
        return True
    except Exception as e:
        print(f"❌ Failed to initialize router: {e}")
        return False

def test_services_module_loads():
    import importlib
    mod = importlib.import_module("src.services.services")
    assert mod is not None

def test_template_files_have_metadata():
    """Test that template files have proper metadata structure."""
    blog_templates = Path("templates/new_blog_templates.yaml")
    code_templates = Path("templates/new_code_templates.yaml")
    kb_templates = Path("templates/kb_templates.yaml")
    docs_templates = Path("templates/docs_templates.yaml")

    assert blog_templates.exists(), "Blog templates not found"
    assert code_templates.exists(), "Code templates not found"
    assert kb_templates.exists(), "KB templates not found"
    assert docs_templates.exists(), "Docs templates not found"

    blog_content = blog_templates.read_text()
    code_content = code_templates.read_text()
    kb_content = kb_templates.read_text()
    docs_content = docs_templates.read_text()

    # Check for metadata structure
    for content, name in [(blog_content, "blog"), (code_content, "code"), 
                          (kb_content, "kb"), (docs_content, "docs")]:
        assert 'id:' in content, f"{name} templates missing id"
        assert 'type:' in content, f"{name} templates missing type"
        assert 'version:' in content, f"{name} templates missing version"
        assert 'schema:' in content, f"{name} templates missing schema"

def test_web_app_has_agent_logs_endpoint():
    """Test that app_unified.py has agent logs endpoint."""
    app_path = Path("src/web/app_unified.py")
    assert app_path.exists(), "app_unified.py not found"

    content = app_path.read_text()

    # Check for agent logs endpoint
    assert '/api/agents/' in content, "Agent logs endpoint missing"
    assert 'redact_secrets' in content, "Secret redaction missing"
